### DISCUSSION TITLE
Any possibility of accessing the keypad input for other automation (e.g. a code that opens the electronic side gate instead)

### DISCUSSION THREAD

**Discussion by mutasim** [technyon/nuki_hub#364] [Q&A] [answered]
Is it possible to set a code that doesn't open the door but rather I can use as an automation trigger to do something else with? 

Or perhaps another creative way of using the keypad input to trigger an automation.

I'm thinking about my electronic side gate lock.

**Comment by technyon** [comment]
Unfortunately no this is not possible. The keypad is paired to the lock, and whatever happens is between the lock and the keypad. The ESP is only notified about state changes as a result.

**Reply by mutasim** [reply]
Thanks - is there any supporting data in the state change? 

E.g. Failed unlock due to expired code, code ID = xxx or invalid code, code = xxxxxx? 

I'm wondering if I could setup expired codes or just using incorrect codes as a workaround... 

(Apologies - I don't have the kit in hand yet to be able to test this stuff)

**Reply by iranl** [reply]
Invalid keypad codes are logged to the authentication log.
If the code exists but is limited to say a minute in the middle of the night on sunday the entering of the code will basically never unlock the door but will be logged with the corresponding id/name of this user.

Nuki Hub has access to this  log, but the implementation on either/both the Nuki and Nuki Hub side is currently not working as it should (at least on my Nuki 4.0 Pro).
I also believe (but not researched this in depth) that the Nuki Lock does not actively signal the Nuki Hub/bridge with the signal that an incorrect code has been entered so that would prevent you from reacting in a timely manner to the entering of an incorrect code.

**Reply by iranl** [reply]
I looked into this some more and based on information from the Nuki devs I understand that the Nuki device signals the (Nuki Hub) bridge of any change that goes into the log. So it might be that Nuki Hub does receive a signal on a failed keypad attempt and can update the authorization log at that time, finding the user belonging to the (very time limited) code and publish this to mqtt. You could than have some node-red/ha etc automation react to that. I'm not sure if this process will be fast enough for your use case and it does require some work on the Nuki Hub side to better deal with the authorization log.

It's on my to do list, but not at the top atm.

**Reply by mutasim** [reply]
Also presumably rather than a very time limited code you could also use a code where enabled = 0 (?)

**Reply by mutasim** [reply]
Is this same capability also required for the following use case? Or can that be handled in a different way?

The house has two entrance doors. A porch door which is in front of the entrance door. You need to unlock both for access to the house. Nuki is on the outer porch door, and a different lock is on the entrance door to the house. 

Some users can have access to the whole house (entrance door unlocks with Nuki porch door) and other users only have access to the porch (like delivery drivers). 

In this case some users will have fingerprint to access others will have code (guests). 

Thanks

**Reply by iranl** [reply]
> Also presumably rather than a very time limited code you could also use a code where enabled = 0 (?)

Haven't tested this, but might work. Question is whether Nuki logs this as an unknown code or a disabled code

> Is this same capability also required for the following use case? Or can that be handled in a different way?

This could possibly be made to work. Keypad codes or fingerprint would unlock the Nuki on the outer door independently from Nuki Hub.

Nuki Hub would pick up the changed lock state and publish the state change and authorizing user to MQTT.

Some smarthome automation (e.g. nodered/Home Assistant) would then unlock the inner door if the authorizing user is on a certain list.

**Reply by mutasim** [reply]
Thanks for the reply.

Ok +1 from me on both uses case please 🙏. 

The double door unlock is definitely a more common/important scenario in my opinion. I didn’t lead with that question as I had wrongly presumed this was already possible somehow.

**Reply by iranl** [reply]
Authorization log is fixed in #368

**Reply by mutasim** [reply]
Wow that was quick! Great work. 

Does this expose the code ID from keypad attempts?

**Reply by iranl** [reply]
It should be able to show anything the official app can show.
I haven't tested it by entering some known (disabled/timelimited) codes with this latest fix at this time yet.
It might just work, but it might need some work still.
Atleast the log now shows the 5 latest log entries instead of entry 2-6 since the lock/opener was put in use.

**Comment by propi62** [comment]
as i understand this conversation, at the moment, it is not possible to enter a different code on the keypad to trigger a homeassisant action to unlock another door? ([garagedoor opener ](https://www.athom.tech/blank-1/garage-door-opener-for-esphome)

**Comment by technyon** [comment]
@propi62 Correct, this is due to limitations in the Nuki bluetooth API.

**Reply by mutasim** [reply]
I thought @iranl latest fixes to the auth logs mean that you might be able to query the lock for the details of a failed attempt and use that for a suitable automation. 

(I don’t yet have the hardware so can’t test)

**Reply by technyon** [reply]
@mutasim Yes you could do that, but it's a workaround and it depending on your use case, and may or may not work well.

**Reply by mutasim** [reply]
Would be great if someone in the community could test disabled/time-limited codes as triggers for automations and report back on speed/reliability etc.

**Reply by mundschenk-at** [reply]
Well yes, please report 😅

**Comment by propi62** [comment]
the nukihub shows the last entered keypad user. so its possible to use different keys for different automatisations. thank you very much.
![image](https://github.com/technyon/nuki_hub/assets/39047802/f05fc31f-f5a4-4798-94b5-55ad18c836ff)

**Reply by mutasim** [reply]
Great - was there any time lag?

Could you perhaps test disabled/time-limited codes? That allows for the keypad to be used for other doors/use cases without unlocking the Nuki lock.

**Reply by propi62** [reply]
it works with disabled keys (lock disabled). (its possible to trigger different actions without locking/unlocking the nukilock.)
homeassistant trigger with (Keypad) needed. (video attached)
![image](https://github.com/technyon/nuki_hub/assets/39047802/f26d7958-19ed-4922-9bf0-3d50d4f9e189)

https://github.com/technyon/nuki_hub/assets/39047802/8746ef8f-fa8d-4333-8774-7e986d76fccb

**Reply by mutasim** [reply]
Thanks for sharing! That looks great 👍 👍

**Comment by iranl** [comment, marked as answer]
The new rollingLog topic that will be introduced in #384 should make for the best topic to base your automation on. It will also be automatically exposed to home assistant discovery as a sensor with all properties shown below as JSON properties in the sensor.

See below for how disabled / timelimited (while used out of the allowed time) / future codes show up in te log.
They will show the name of the authorization, authorizationId and the completion state and value.
This value is 9 for known codes that don't allow access at the time they are used (because they are disabled, timelimited etc.)
I need to add this value to the list of possibilities so the state does not show as `undefined` but as something like `notallowed` or `notauthorized`, but you can already use `completionStatusVal` in your automations

```
{
    "index": 3347,
    "authorizationId": 80405,
    "authorizationName": "Test",
    "timeYear": 2024,
    "timeMonth": 5,
    "timeDay": 31,
    "timeHour": 6,
    "timeMinute": 29,
    "timeSecond": 30,
    "type": "KeypadAction",
    "action": "Unlatch",
    "completionStatus": "undefined",
    "completionStatusVal": 9
  }
```

**Comment by iranl** [comment]
Auth log should be fully implemented with 8.35

**Comment by propi62** [comment]
after many hours of testing, i cant make it work properly. (with homeassistant)
Triggering actions with keypad works, but after nukehub reboot, the last action triggers again.
I think the sensor.nuki_garage_rolling_authorization_log     attribute: index changes after reboot for a milisecond?
I dont know how to solve it.

```
alias: Nuki Keypad Garage
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.nuki_garage_rolling_authorization_log
    enabled: true
    for:
      hours: 0
      minutes: 0
      seconds: 1
    attribute: index
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.nuki_garage_rolling_authorization_log
            attribute: authorizationName
            state: haustuer (Keypad)
        sequence:
          - service: lock.unlock
            target:
              entity_id: lock.lock_hausture
            data: {}
            enabled: false
          - service: notify.mobile_app_frederic_mobile
            data:
              title: haustur (Keypad) wurde ausgelöst
              message: ""
        alias: Haustuer
```

**Reply by mutasim** [reply]
Have you tried the latest build (from master)? I [believe there's been some work to address the repeats on reboot](https://github.com/technyon/nuki_hub/issues/408#issuecomment-2182921827). I haven't managed to test it yet.

**Reply by propi62** [reply]
no, i never figured out how to build from master. i always use releases for updates. atm im using: 8.35

**Reply by mutasim** [reply]
Here you go:

https://github.com/technyon/nuki_hub/actions/runs/9845748890

(The builds are all listed under artefacts)

I believe these builds need to be flashed using USB/serial for the first time because of changes to the partition table. (I can't tell you more than that.. I'm just repeating what I've read!)

**Reply by propi62** [reply]
i flashed nuki_hub_esp32.bin over webinterface.
still triggers on nukihub reboot: (garagedoor is wide open in the morning if nukihub reboots at night ;)

```
platform: state
entity_id:
  - sensor.nuki_garage_rolling_authorization_log
enabled: true
for:
  hours: 0
  minutes: 0
  seconds: 1
attribute: index
not_from:
  - unavailable
  - unknown
not_to:
  - unavailable
  - unknown
```
