### ISSUE TITLE
Feature request: Auto discovery for presence detected devices in Home Assistant

### ISSUE THREAD

**Issue by bcutter** [technyon/nuki_hub#159]
The ability of doing presence detection with NUKI Hub is a quite powerful feature.

Unfortunately it is not very well known (but stated in the docs ✅).

And most important: having that information in MQTT currently is the "end of the road" for most normal users (not being into templating that much or at all) resulting in not using that "free lunch information" at all. 

---

FR:

1) Add a config option "publish Bluetooth presence devices to Home Assistant"
2) Enable auto discovery for presence detected devices, so for every device a `device_tracker.abc` entity is automatically created and updated if the state changes.
3) We probably need a logic and config option like "presence timeout": after XX seconds devices not discovered anymore are set from "home" to "not_home".

---

That would make NUKI hub such a powerful Bluetooth device tracker and be probably one of THE best add-on features.

**Comment by ralle12345** [comment]
I would like to add that if would be useful to also publish the rssi of the received beacon per presence device

**Comment by thor9898** [comment]
is this some kind of ESPresense?

**Comment by technyon** [comment]
This feature is out of scope for NUKI Hub. Let me explain

- First of all, it'll take time to implement and test
- It adds complexity to the code for a feature that's in the focus of this project. This means possible new bugs, time for maintenance that can go into more relevant features
- It eats up ressources on the ESP which can be used for more relevant features

Since ESPs are inexpensive, I suggest to use another ESP for presence tracking.

@ralle12345 The rssi value per device is available, you can read it from the published CSV data.

**Comment by bcutter** [comment]
As the information is there, one should do something with it. Following the basically completely understandable "not in core focus of this project" approach, otherwise one could ask why it exists at all.

If one has ideas / working snippets on how to create and update `device_tracker` entities in Home Assistant based on the currently available MQTT topics please let us (me) know.

**Comment by mundschenk-at** [comment]
@bcutter You do not _really_ want to add a `device_tracker` for every BLE beacon picked up by the Nuki Hub, as this would add a tracker for every MiFlora sensor and Philips Hue bulb in range of the hub.

**Comment by bcutter** [comment]
Indeed I want to monitor only _specific_ Bluetooth devices. Underlying main task remains the same: use MQTT data to create and update device tracker entity.

**Comment by mundschenk-at** [comment]
https://espresense.com

**Comment by technyon** [comment]
The reason this exists is that it is a by-product of something that needs to be done anyway: scanning for beacons. This is necessary for 1. pairing the lock and 2. detecting lock state changes. The information about beacons is always collected, wether presence detection is enabled or not. If enabled, it's just packed into a CSV payload and published. That's easy. And parsing data from CSV is possible, just less convenient.

Making a UI to allow to configure which beacons to track, then dynamically publishing discovery topics, deleting them when necessary and so on adds a layer of complexity that's time-consuming to implement. And it doesn't stop at implementation. features need to be tested before release and if changes are made to the code. After release, it'll need maintenance (e. g. reported bugs that need to be fixed and so on). Considering there's already a firmware that takes care all of this and does it well, I think it's better to just that firmware on a secondary ESP.

**Comment by bcutter** [comment]
I understand Nuki Hub won't provide anything besideds the raw presence detection data. It would be great to get some kickstart assistance on how to realize this on a "for one device only" basis.

So: **Can someone help on how to create some kind of template sensor for one specific bluetooth device out of the presence topic?**

Target: create a sensor which contains the connection strength of a certain bluetooth device nearby one SL/Nuki Hub (the `/nuki_smartlock/presence/devices` topic contains bluetooth devices discovered by the Nuki Hub, not the SL, right?).
Sensor value should contain the connection strength if available or show 'unavailable' or '0' in case the device is not discovered.

Example input (one line/entry of the presence/devices topic): `XX:XX:XX:XX:XX:XX;Device name;-62`

In the end I want to use the sensor in an automation (Home Assistant) as trigger/condition (like "once state sensor.device_name >= -50, do something").

**Comment by mundschenk-at** [comment]
Not tested, but something like

```yaml
mqtt:
  sensor:
    - name: "<device name>"
      unique_id: '<uuid>'
      state_topic: "<nuki topic>/presence/devices"
      value_template: >
         {%- for line in value.split('\n') -%}
              {%- if line[:17] == 'XX:XX:XX:XX:XX:XX' -%}
                 {{ line[-3:] }}
              {%- endif -%}
         {%- endfor -%}
      device:
        identifiers: nuki_<device>
```

However, this question would be more suitable to https://community.home-assistant.io/, as it is not really specific to Nuki Hub.

**Comment by bcutter** [comment]
Indeed the forum is better. It's just that your piece is working, except being unable to set a "default" state if the stuff in the for loop does not apply.

Even this is great for starting, after now more than 30 minutes I was unable to modify it to just show "home" once a certain MAC is discovered and show "not_home" if it is not. So it's a pretty pain in the a** unfortunately.

**Comment by madface303** [comment]
I know this is not the home assistant forum, but maybe it would help the one or other. Just create a mqtt sensor:
```
mqtt:
  sensor:
    - name: "nuki_presence_sensor"
      state_topic: "nuki/presence/devices"
      value_template: "{{ 'home' if 'YOUR-iBEACON-ID' in value else 'not_home' }}"
      unique_id: "nuki/presence/devices_uid"
```
Then you have a sensor if your iBeacon ID is recognized by NukiHUB, home if recognized and not_home if you are away.

**Comment by xaris33** [comment]
> I know this is not the home assistant forum, but maybe it would help the one or other. Just create a mqtt sensor:
> 
> ```
> mqtt:
>   sensor:
>     - name: "nuki_presence_sensor"
>       state_topic: "nuki/presence/devices"
>       value_template: "{{ 'home' if 'YOUR-iBEACON-ID' in value else 'not_home' }}"
>       unique_id: "nuki/presence/devices_uid"
> ```
> 
> Then you have a sensor if your iBeacon ID is recognized by NukiHUB, home if recognized and not_home if you are away.

Thank you, this works great.

Any idea how we could extract the rssi as well to a sensor?

**Comment by madface303** [comment]
Sure, here you only use value instead of the if clause:
```
mqtt:
  sensor:
    - name: "nuki_esp32_lock_rssi"
      state_topic: "nuki/lock/rssi"
      value_template: "{{ value }}"
      unique_id: nuki_esp32_nuki_lock_rssi_unique_id
```
