### ISSUE TITLE
in home assistant the lock status of jammed cannot be shown?

### ISSUE THREAD

**Issue by bertybassett** [technyon/nuki_hub#163]
what am I doing wrong?

**Comment by technyon** [comment]
The status only shows locked or unlocked. You can however look into the MQTT tree to see the actual status (lock/state).

**Comment by bertybassett** [comment]
```
mqtt:
  sensor:
    - name: "nuki_motorstatus"
      unique_id: '12bAAA3asde'
      state_topic: "nuki/lock/state"
```
Was the answer shame the auto discovery on home assistant does not include this information
