### ISSUE TITLE
Opener - ring detect sensor not working

### ISSUE THREAD

**Issue by bklaesener** [technyon/nuki_hub#215]
Hi, my "ring detect" sensor is always shown as "unknown" on the MQTT device page.

According to the MQTT debug log, the payload should be either "ring" or "locked" (see below).

Instead, each ring action returns a "continous mode" payload, which appears to match the "lock/state" state_topic but does not serve the purpose of the sensor:

-----------------------------------

Transmitted messages:
Downstairs Door ring detect (binary_sensor.downstairs_door_ring_detect)
MQTT discovery data:
   Topic: homeassistant/binary_sensor/xxxxxxxx/ring/config
Payload
device:
  identifiers:
    - nuki_xxxxxxxx
  manufacturer: Nuki
  model: Opener
  name: Downstairs Door
name: Downstairs Door ring detect
unique_id: xxxxxxxx_ring_detect
device_class: sound
state_topic: nukiopener/lock/state
payload_on: ring
payload_off: locked
platform: mqtt

Subscribed topics:
nukiopener/lock/state
10 most recently received message(s)
Received 10:56:23
QoS: 0
Payload: ContinuousMode
Received 16:33:50
QoS: 0
Payload: ContinuousMode
Received 16:34:07
QoS: 0
Payload: ContinuousMode

-----------------------------------

If this is due to a misconfiguaration on my part I would be grateful for a hint.

**Comment by bklaesener** [comment]
Thanks, I now read up across different forums on your previous endeavors to implement the ring detect sensor. It appears that Nuki chose to only make ring detection available via the HTTP Bridge API - too bad.

I note that I get a sequence of at least two, sometimes three "Continuous Mode" messages within 10 to 12 seconds for each press of the doorbell button:

                {
                  "payload": "ContinuousMode",
                  "qos": 0,
                  "retain": 0,
                  "time": "2023-08-04T09:04:12.498879+00:00",
                  "topic": "nukiopener/lock/state"
                },
                {
                  "payload": "ContinuousMode",
                  "qos": 0,
                  "retain": 0,
                  "time": "2023-08-04T09:04:14.555939+00:00",
                  "topic": "nukiopener/lock/state"
                },
                {
                  "payload": "ContinuousMode",
                  "qos": 0,
                  "retain": 0,
                  "time": "2023-08-04T09:04:22.609038+00:00",
                  "topic": "nukiopener/lock/state"
                },
                {
                  "payload": "ContinuousMode",
                  "qos": 0,
                  "retain": 0,
                  "time": "2023-08-04T09:28:45.179987+00:00",
                  "topic": "nukiopener/lock/state"
                },
                {
                  "payload": "ContinuousMode",
                  "qos": 0,
                  "retain": 0,
                  "time": "2023-08-04T09:28:56.402881+00:00",
                  "topic": "nukiopener/lock/state"
                }

I am not sure why it is a sequence of messages - it may depend on the lenght of the press.

So maybe you could try adapting your current detection mechanism (state "locked" updates to state "locked") to also pick up updates from "ContinuousMode" to "ContinuousMode" (and disregard any further "updates" happening within x seconds of the initial one).

**Comment by technyon** [comment]
Yes makes sense they implemented it in a similar way, but those repeating messages are strange. The question is how long to ignore them.

**Comment by mundschenk-at** [comment]
As a complication, might this also be affected by the ring tone suppression setting?

**Comment by bklaesener** [comment]
> Yes makes sense they implemented it in a similar way, but those repeating messages are strange. The question is how long to ignore them.

I did some more test runs. Each doorbell button press triggers 2 or 3 (never only 1) "ContinuousMode" messages. The last message is logged within 2 to 14 seconds of the first. So a 20-second cool-off period counting from the first message would seem relatively safe.

There are single message events, too, but they are never triggered by "system" (nukihub) actions, only by "manual" or "button" actions (or - strangely - are logged without any trigger and with no corresponding entry in the Nuki app log).

**Comment by bklaesener** [comment]
> As a complication, might this also be affected by the ring tone suppression setting?

I do not have ring tone suppression activated, neither globally nor in connection with Continuous mode. Should I test with active suppression?

**Comment by mundschenk-at** [comment]
Yeah, I think that would be helpful.

**Comment by bklaesener** [comment]
Ok, will do more tests tomorrow and report back.

**Comment by bklaesener** [comment]
A few more observations:

- It does not appear to make any difference whether or not ring tone suppression is enabled.
- Contrary to my previous observation, "system" and "button" actions _do_ trigger multiple consecutive messages under the nukiopener/lock/state topic; single messages are generated only when there is no actual trigger event.
- Based on more than a dozen tests, the longest period from the first to the last nukiopener/lock/state message remains at 14 seconds, which was a single outlier. In most cases it is a maximum of 5 seconds.

In the meantime I have implemented a ring notification that works while continuous mode is active with the following automation in Home Assistant:

```
alias: House Door unlatched by doorbell notification
description: ""
trigger:
  - platform: mqtt
    topic: nukiopener/lock/state
condition:
  - condition: template
    value_template: "{{ is_state('sensor.downstairs_door_trigger', 'manual') }}"
action:
  - if:
      - condition: state
        entity_id: timer.opener_trigger
        state: idle
    then:
      - service: timer.start
        data: {}
        target:
          entity_id: timer.opener_trigger
    else:
      - service: timer.finish
        data: {}
        target:
          entity_id: timer.opener_trigger
      - service: notify.mobile_app_xxx
        data:
          message: House door unlatched by doorbell
mode: parallel
max: 2
```
The timer.opener_trigger entity is a timer helper with a defined duration of 20 seconds. Its state is either "idle" or "active".

When a message under the nukiopener/lock/state topic is received for the first time, the timer is started. While continuous mode is active, the message is always "ContinuousMode", so there is no need to filter for message content. It is, however, important to filter for the trigger sensor value being "manual" in order to catch only actual doorbell button presses and not other opening actions.

When a second message within a 20 second period is received (i.e. while the timer is active), the timer is stopped and the notification action is executed.
