### ISSUE TITLE
configuration/autoLock not showing up in Home Assistant

### ISSUE THREAD

**Issue by bjiirn** [technyon/nuki_hub#261]
In Home Assistant the AutoLock Function is not showing up in the Configurations.

Does anyone have an idea why that could be or how to fix that?

When i Look at the MQTT messages it shows up.
I don't know much about MQTT and how Auto Discovery works tho.

![image](https://github.com/technyon/nuki_hub/assets/47543428/e7402a51-2527-406b-af7d-35ed3072c2a1)
![image](https://github.com/technyon/nuki_hub/assets/47543428/0925fa13-ef83-440d-a533-ab475d580826)

**Comment by technyon** [comment]
I think auto discovery for auto lock is not implemented yet, it could be added though.

**Comment by bjiirn** [comment]
Ah, ok. Thanks for the clarification. 
It would be grate if that were part of the DeviceConfig,
but for now i got it working as a separate entity with this in my configuration.yaml :
```
mqtt:
  - switch:
      unique_id: nuki_autolock
      name: "Nuki Auto Lock"
      state_topic: "nuki/configuration/autoLock"
      command_topic: "nuki/configuration/autoLock"
      payload_on: "1"
      payload_off: "0"
      state_on: "1"
      state_off: "0"
```

**Comment by mundschenk-at** [comment]
You can have the switch appear in your device by adding a `device` section to your YAML:

```yaml
  device:
    identifiers: nuki_<device>
    name: <Device Name>
```
