### ISSUE TITLE
Incorrect `Hybrid connected` entity for Opener

### ISSUE THREAD

**Issue by mundschenk-at** [technyon/nuki_hub#540]
### PROBLEM DESCRIPTION
A spurious entity `Hybrid connected` is discovered for the Opener when the Lock is paired in Hybrid Mode. 

```yaml
unique_id: <OPENERID>_hybrid_connected
payload_off: '0'
payload_on: '1'
device:
  identifiers:
    - nuki_<OPENERID>
enabled_by_default: true
name: Hybrid connected
state_topic: nukihub/lock/hybridConnected
entity_category: diagnostic
availability:
  topic: nukihub/maintenance/mqttConnectionState
```

### REQUESTED INFORMATION

- [x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [x] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x] Device used (e.g., ESP32-S3): ESP32-S3
- [x] Nuki Hub binary firmware version number used: 9.02
  - [x] Pre-compiled
  - [ ] Self-compiled
- [ ] Provide the output of http://nukihubIP/info: irrelevant

### TO REPRODUCE
Pair a SL in Hybrid Mode and an Opener to the same NH.

### EXPECTED BEHAVIOUR
There should be no `Hybrid Mode` entity for the Opener (at least until Nuki makes a Matter-enabled Opener). Either the entity should be moved the Nuki Hub device or not created for the Opener.
