### ISSUE TITLE
Unable to add new keypad user

### ISSUE THREAD

**Issue by DaveGalbraith** [technyon/nuki_hub#55]
I am having trouble getting the add a new keypad user process to work. Everything else seems to work well (great job btw!), for example, I can delete a user that I have previously created using the Nuki app. But If I run a HA script to add a new user I get a failed commandResult (monitored using MQTT Explorer). I am running the Mosquito broker add-on in HA. Below are my script yaml's:

```
alias: "Nuki: Add New User Code"
sequence:
  - service: mqtt.publish
    data:
      topic: nuki/keypad/command/name
      payload: fred
      qos: "2"
  - service: mqtt.publish
    data:
      topic: nuki/keypad/command/code
      payload: "123456"
      qos: "2"
  - service: mqtt.publish
    data:
      topic: nuki/keypad/command/enabled
      payload: "1"
      qos: "2"
  - service: mqtt.publish
    data:
      topic: nuki/keypad/command/action
      payload: add
      qos: "2"
mode: single

```

```
alias: "Nuki: Delete User Code "
sequence:
  - service: mqtt.publish
    data:
      topic: nuki/keypad/command/id
      payload: "4"
      qos: "0"
  - service: mqtt.publish
    data:
      topic: nuki/keypad/command/action
      payload: delete
      qos: "0"
mode: single

```
Any help or pointers to aid debugging will be greatly appreciated.

Also, I did not see any way to set time limited access on the keypad codes. Is this possible using nuki_hub and, if not, are there plans to introduce such functionality?
